permalink: /:title.html

auto: true
pygments: true
markdown: rdiscount

title: 芝麻小站
tagline: 张慧敏的芝麻小站 - ZHM.me
about: I am HuiMin Zhang. Welcome and thanks for reading...

author :
  name : 张慧敏
  email : zikercn@gmail.com
  feed : /atom.xml
  qq : 280188858

production_url : http://zhm.me

JB :
  version : 0.2.13

  BASE_PATH : false

  ASSET_PATH : false

  comments :
    provider : disqus
    disqus :
      short_name : zhmme
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-33270091-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  sharing :
    provider : custom

  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

